
export default new Map([
["src/content/docs/about.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fabout.mdx&astroContentModuleFlag=true")],
["src/content/docs/blogs/culture-and-places.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblogs%2Fculture-and-places.mdx&astroContentModuleFlag=true")],
["src/content/docs/blogs/finance-bitcoin-crypto.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblogs%2Ffinance-bitcoin-crypto.mdx&astroContentModuleFlag=true")],
["src/content/docs/blogs/personal-writing.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblogs%2Fpersonal-writing.mdx&astroContentModuleFlag=true")],
["src/content/docs/blogs/tech-blogs.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblogs%2Ftech-blogs.mdx&astroContentModuleFlag=true")],
["src/content/docs/blogs/travel.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblogs%2Ftravel.mdx&astroContentModuleFlag=true")],
["src/content/docs/communities/forums.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcommunities%2Fforums.mdx&astroContentModuleFlag=true")],
["src/content/docs/communities/small-communities.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcommunities%2Fsmall-communities.mdx&astroContentModuleFlag=true")],
["src/content/docs/contribute.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcontribute.mdx&astroContentModuleFlag=true")],
["src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/website-tools/blogging-platforms.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fwebsite-tools%2Fblogging-platforms.mdx&astroContentModuleFlag=true")],
["src/content/docs/website-tools/hosting.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fwebsite-tools%2Fhosting.mdx&astroContentModuleFlag=true")],
["src/content/docs/website-tools/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fwebsite-tools%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/website-tools/self-hosting-apps.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fwebsite-tools%2Fself-hosting-apps.mdx&astroContentModuleFlag=true")],
["src/content/docs/website-tools/self-hosting.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fwebsite-tools%2Fself-hosting.mdx&astroContentModuleFlag=true")]]);
		